version: '2'

services:
  varnish:
    build: varnish/
    hostname: varnish
    container_name: varnishserver
    restart: always
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - ${VARNISH_PORT}:6081
    depends_on:
      - apache
    links:
      - apache

  apache:
    build:      
      context: ./apache2
    hostname: php
    container_name: phpserver
    restart: always
    ports:
      - ${APACHE_HOST_HTTP_PORT}:8080
      - 8081:8081
      - ${APACHE_HOST_HTTPS_PORT}:443
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ${APP_CODE_PATH_HOST2}:/var/www/html/outros_sites
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlserver
    hostname: msql
    image: mysql:5.6
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ${DATA_PATH_HOST}:/var/lib/mysql 
      - ${DOWNLOAD_PATH_HOST}:/var/dowload   
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app_development
  
  phpma:
    container_name: myaserver
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpma
    links:
      - mysqldb
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1  

  mysqldb57:
    image: mysql:5.7.29
    container_name: mysqlserver57
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST_57}:/var/lib/mysql 
      - ${DOWNLOAD_PATH_HOST}:/var/dowload